from pathlib import Path
from datetime import datetime
from textwrap import dedent

def save_document(response_text: str, directory: str = "./output") -> str | None:
    """Export travel plan to a Markdown file in `directory`."""
    ts = datetime.now().astimezone()
    header_ts = ts.strftime("%Y-%m-%d at %H:%M %Z")
    file_ts = ts.strftime("%Y-%m-%d_%H-%M-%S")

    out_dir = Path(directory)
    out_dir.mkdir(parents=True, exist_ok=True)
    filename = out_dir / f"AI_Trip_Planner_{file_ts}.md"

    markdown_content = dedent(f"""\
    # 🌍 AI Travel Plan

    **Generated:** {header_ts}  
    **Created by:** Meet's Travel Agent

    ---

    {response_text}

    ---

    _This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip._
    """)

    try:
        filename.write_text(markdown_content, encoding="utf-8")
        print(f"Markdown file saved as: {filename}")
        return str(filename)
    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None